// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Card': typeof import("../components/Card.vue")['default'],
    'StarCard': typeof import("../components/StarCard.vue")['default'],
    'TheButton': typeof import("../components/TheButton.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheNavbar': typeof import("../components/TheNavbar.vue")['default'],
    'TheTag': typeof import("../components/TheTag.vue")['default'],
    'TheTags': typeof import("../components/TheTags.vue")['default'],
    'TipCard': typeof import("../components/TipCard.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyCard': typeof import("../components/Card.vue")['default'],
    'LazyStarCard': typeof import("../components/StarCard.vue")['default'],
    'LazyTheButton': typeof import("../components/TheButton.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheNavbar': typeof import("../components/TheNavbar.vue")['default'],
    'LazyTheTag': typeof import("../components/TheTag.vue")['default'],
    'LazyTheTags': typeof import("../components/TheTags.vue")['default'],
    'LazyTipCard': typeof import("../components/TipCard.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Card: typeof import("../components/Card.vue")['default']
export const StarCard: typeof import("../components/StarCard.vue")['default']
export const TheButton: typeof import("../components/TheButton.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheNavbar: typeof import("../components/TheNavbar.vue")['default']
export const TheTag: typeof import("../components/TheTag.vue")['default']
export const TheTags: typeof import("../components/TheTags.vue")['default']
export const TipCard: typeof import("../components/TipCard.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyCard: typeof import("../components/Card.vue")['default']
export const LazyStarCard: typeof import("../components/StarCard.vue")['default']
export const LazyTheButton: typeof import("../components/TheButton.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheNavbar: typeof import("../components/TheNavbar.vue")['default']
export const LazyTheTag: typeof import("../components/TheTag.vue")['default']
export const LazyTheTags: typeof import("../components/TheTags.vue")['default']
export const LazyTipCard: typeof import("../components/TipCard.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
