// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Card': typeof import("../components/Card.vue")['default'],
    'PackageCard': typeof import("../components/PackageCard.vue")['default'],
    'StarCard': typeof import("../components/StarCard.vue")['default'],
    'TheButton': typeof import("../components/TheButton.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheLinkButton': typeof import("../components/TheLinkButton.vue")['default'],
    'TheNavbar': typeof import("../components/TheNavbar.vue")['default'],
    'TheTag': typeof import("../components/TheTag.vue")['default'],
    'TheTags': typeof import("../components/TheTags.vue")['default'],
    'TipCard': typeof import("../components/TipCard.vue")['default'],
    'TopicSelector': typeof import("../components/TopicSelector.vue")['default'],
    'ContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default'],
    'ContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default'],
    'ContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default'],
    'ContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default'],
    'ContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default'],
    'Markdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default'],
    'MarkdownRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default'],
    'ProseA': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default'],
    'ProseBlockquote': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default'],
    'ProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default'],
    'ProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default'],
    'ProseEm': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default'],
    'ProseH1': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default'],
    'ProseH2': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default'],
    'ProseH3': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default'],
    'ProseH4': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default'],
    'ProseH5': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default'],
    'ProseH6': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default'],
    'ProseHr': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default'],
    'ProseImg': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default'],
    'ProseLi': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default'],
    'ProseOl': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default'],
    'ProseP': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default'],
    'ProseStrong': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default'],
    'ProseTable': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default'],
    'ProseTbody': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default'],
    'ProseTd': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default'],
    'ProseTh': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default'],
    'ProseThead': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default'],
    'ProseTr': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default'],
    'ProseUl': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyCard': typeof import("../components/Card.vue")['default'],
    'LazyPackageCard': typeof import("../components/PackageCard.vue")['default'],
    'LazyStarCard': typeof import("../components/StarCard.vue")['default'],
    'LazyTheButton': typeof import("../components/TheButton.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheLinkButton': typeof import("../components/TheLinkButton.vue")['default'],
    'LazyTheNavbar': typeof import("../components/TheNavbar.vue")['default'],
    'LazyTheTag': typeof import("../components/TheTag.vue")['default'],
    'LazyTheTags': typeof import("../components/TheTags.vue")['default'],
    'LazyTipCard': typeof import("../components/TipCard.vue")['default'],
    'LazyTopicSelector': typeof import("../components/TopicSelector.vue")['default'],
    'LazyContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default'],
    'LazyContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default'],
    'LazyContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default'],
    'LazyContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default'],
    'LazyContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default'],
    'LazyMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default'],
    'LazyMarkdownRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default'],
    'LazyProseA': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default'],
    'LazyProseBlockquote': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default'],
    'LazyProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default'],
    'LazyProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default'],
    'LazyProseEm': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default'],
    'LazyProseH1': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default'],
    'LazyProseH2': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default'],
    'LazyProseH3': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default'],
    'LazyProseH4': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default'],
    'LazyProseH5': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default'],
    'LazyProseH6': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default'],
    'LazyProseHr': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default'],
    'LazyProseImg': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default'],
    'LazyProseLi': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default'],
    'LazyProseOl': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default'],
    'LazyProseP': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default'],
    'LazyProseStrong': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default'],
    'LazyProseTable': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default'],
    'LazyProseTbody': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default'],
    'LazyProseTd': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default'],
    'LazyProseTh': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default'],
    'LazyProseThead': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default'],
    'LazyProseTr': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default'],
    'LazyProseUl': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Card: typeof import("../components/Card.vue")['default']
export const PackageCard: typeof import("../components/PackageCard.vue")['default']
export const StarCard: typeof import("../components/StarCard.vue")['default']
export const TheButton: typeof import("../components/TheButton.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheLinkButton: typeof import("../components/TheLinkButton.vue")['default']
export const TheNavbar: typeof import("../components/TheNavbar.vue")['default']
export const TheTag: typeof import("../components/TheTag.vue")['default']
export const TheTags: typeof import("../components/TheTags.vue")['default']
export const TipCard: typeof import("../components/TipCard.vue")['default']
export const TopicSelector: typeof import("../components/TopicSelector.vue")['default']
export const ContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default']
export const ContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default']
export const ContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default']
export const ContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default']
export const Markdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default']
export const MarkdownRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default']
export const ProseA: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyCard: typeof import("../components/Card.vue")['default']
export const LazyPackageCard: typeof import("../components/PackageCard.vue")['default']
export const LazyStarCard: typeof import("../components/StarCard.vue")['default']
export const LazyTheButton: typeof import("../components/TheButton.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheLinkButton: typeof import("../components/TheLinkButton.vue")['default']
export const LazyTheNavbar: typeof import("../components/TheNavbar.vue")['default']
export const LazyTheTag: typeof import("../components/TheTag.vue")['default']
export const LazyTheTags: typeof import("../components/TheTags.vue")['default']
export const LazyTipCard: typeof import("../components/TipCard.vue")['default']
export const LazyTopicSelector: typeof import("../components/TopicSelector.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default']
export const LazyContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default']
export const LazyContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default']
export const LazyContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default']
export const LazyContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default']
export const LazyMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default']
export const LazyMarkdownRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default']
export const LazyProseA: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default']
export const LazyProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProseEm: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
